name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_IPTECH_KEY }}

      - name: Verify and add host key
        run: |
          ssh-keyscan -p 22332 -H webserver.sudo.az >> ~/.ssh/known_hosts

      - name: Deploy to Production
        if: github.ref_name == 'main'
        run: |
          ssh -p 22332 iptech@webserver.sudo.az /bin/bash <<EOF
            set -e
            sudo iptech deploy iptech-frontend
          EOF
